### ISSUE TITLE
展示下拉框时报错

### ISSUE THREAD

**Issue by lijiawei0602** [iblq/antd-virtual-select#17]
![image](https://user-images.githubusercontent.com/23008158/76842407-305bb400-6875-11ea-9ee0-caf78571ed6e.png)

**Comment by iblq** [comment]
今天刚刚更新过，修复了这个问题，请更新到做新版 1.0.5 试试

**Comment by Aaallan** [comment]
您好，更新到1.0.5还是有这个问题
![image](https://user-images.githubusercontent.com/36944529/77379291-36094a80-6ddd-11ea-95d4-96d4e0e06413.png)

**Comment by iblq** [comment]
> 您好，更新到1.0.5还是有这个问题
> ![image](https://user-images.githubusercontent.com/36944529/77379291-36094a80-6ddd-11ea-95d4-96d4e0e06413.png)
很抱歉，确实存在问题，刚刚修复，之前的 actions 自动发布存在问题

**Comment by Aaallan** [comment]
十分感谢！这个ticket应该可以close了
