### ISSUE TITLE
引用时传入dropdownClassName无效

### ISSUE THREAD

**Issue by akeymo** [iblq/antd-virtual-select#22]
代码里写死了`dropdownClassName`，这样外部引用时传入这个属性并不会被传给`antd`
这段代码是否修改成别的变量名，最后传入的时候拼接这个变量名和外部传入的`dropdownClassName`会更好？
```
this.dropdownClassName = `dc${+new Date()}`;
```

**Comment by iblq** [comment]
已修复添加 dropdownClassName 属性无效问题，请更新到最新版本 v1.1.0 使用
