### ISSUE TITLE
Form表单运用场景下,会出现下拉滚动内容留白,下一次滚动会定位到上次选择内容位置

### ISSUE THREAD

**Issue by UnicornXU** [iblq/antd-virtual-select#23]
1. 在线Demo
https://codesandbox.io/s/superselect-iijkg

**Comment by iblq** [comment]
已修复，v1.1.1

**Comment by UnicornXU** [comment]
谢谢大佬,我更新试用下

**Comment by a879475908123** [comment]
大佬  会出现下拉滚动内容留白这个问题在变成AutoComplete组件的时候并没有解决啊
![image](https://user-images.githubusercontent.com/44834460/91634520-a1f27d80-ea23-11ea-974b-677c2631ea27.png)

**Comment by a879475908123** [comment]
@iblq

**Comment by a879475908123** [comment]
大佬 会出现下拉滚动内容留白这个问题在变成AutoComplete组件的时候并没有解决啊
![image](https://user-images.githubusercontent.com/44834460/91634567-e1b96500-ea23-11ea-8198-c04db4a7a8bf.png)
